### ISSUE TITLE
Roadmap for v4

### ISSUE THREAD

**Issue by danthorpe** [ProcedureKit/ProcedureKit#398]
For information regarding Xcode 8, please [see the wiki](https://github.com/ProcedureKit/ProcedureKit/wiki/Xcode-8).
# Phase 1 - Organization
- [x] Move repository to [ProcedureKit](https://github.com/ProcedureKit/ProcedureKit)
- [x] Rename _Operations_ to _ProcedureKit_ in README, and other areas
- [x] Update header logo - #399
- [x] Set ProcedureKit org logo
- [x] Add Code of Conduct & Contribution guidelines - #400
# Phase 2 - Project Structure
- [x] Setup project structure with empty frameworks - #401 
- [x] Sort out CI so that all projects are always built - #403, #404
# Phase 3 - The Grand Renaming & Swift 3

At each stage we need to move code into the correct frameworks inside the ProcedureKit project. For each ticket the files/types must be renamed, and made Swift 3 compatible.

We're going to have a number of beta releases for 4.0. This _roadmap_ ticket will list the features which will make it into each beta.
## Beta 1

This is the basic core stuff - minimal  fancy stuff.
### ProcedureKit
- [x] #405: `ProcedureProtocol`, `Procedure`, `ProcedureQueue` etc
- [x] #428: Logging
- [x] #430: `Group` phase 1
- [x] #439: `UserIntent`
- [x] #446: `Result` - can it be added intrinsically to `Procedure`?
- [x] #429: Dependencies and `Condition`
- [x] #442 Add stress tests
- [x] #437 : Errors e.g. from `Group` and result injection
- [x] #447 : Unit test coverage for ResultInjection is incomplete
- [x] #448: Mutual exclusive conditions
- [x] #449: `DelayProcedure`
- [x] #450: `BlockProcedure`
- [x] #468: Rename `Group` to `GroupProcedure`
- [x] #467: `ProcedureKit.podspec`
### TestingProcedureKit
- [x] #405: `TestProcedure`, `ProcedureTestCase`, basic tests for cancellation, finishing, 
- [x] #430: `GroupTestCase`
- [x] #422: `StressTestCase` 
- [x] #429: Add `XCTAssertProcedure` functions - to make asserting `Procedure` behaviour consistent.
## Beta 2: #493

Beta 2 is fleshing out the _useful_ stuff, such as additional conditions and observers.
### ProcedureKit
- [x] #480: `BlockObserver`
- [x] #470: `NoFailedDependenciesCondition`
- [x] #473: `BlockCondition`
- [x] #471: `NegatedCondition`
- [x] #472: `SilentCondition`
- [x] #475: `TimeoutObserver`
- [x] #478: `ComposedProcedure`
- [x] #478: `GatedProcedure`
- [x] #488: `RepeatedProcedure` & associated generators
- [x] #491: `RetryProcedure`
- [x] #492: `CapabilityProtocol` & associated helpers
## Beta 3: #517

Beta 3 adds more _ProcedureKit_ functionality and provides additional specialist functionality for iOS, tvOS and macOS.
### ProcedureKit
- [x] #497: `TransformProcedure` (previously `MapProcedure` in Beta 2)
- [x] #497: `MapProcedure`
- [x] #497: `FlatMapProcedure`
- [x] #496: `FilterProcedure`
- [x] #497: `ReduceProcedure`
### ProcedureKitMobile
- [x] #476: `BackgroundObserver`
- [x] #498: `NetworkObserver`
### ProcedureKitLocation
- [x] #499: `Capability.Location`
- [x] #500: `UserLocationProcedure`
- [x] #502: `ReverseGeocodeProcedure`
- [x] #504: `ReverseGeocodeUserLocationProcedure`

## Beta 4: #560

Beta 4 has ~~quite a few small~~ many bug fixes and API improvements. For example, result injection has a slightly different api, and now uses `PendingValue` to avoid the use of explicitly unwrapped optionals. Additionally Beta 4 adds _ProcedureKitNetwork_ and _ProcedureKitCloud_ frameworks, with full support via CocoaPods and specs. For example, to include _ProcedureKitNetwork_ code:

``` ruby
pod 'ProcedureKit/Network', :git => 'https://github.com/procedurekit/procedurekit'
```
### ProcedureKit
- [x] #516: `AnyProcedure<Requirement, Result>` 
- [x] #508: Podspec
- [x] #536: `.then { }` API
- [x] #541: `ResultInjection` protocol now uses `PendingValue<T>` to avoid the need for explicitly unwrapped optionals.
### ProcedureKitNetwork
- [x] #525: `NetworkDataProcedure`
- [x] #537: `ResilientNetworkProcedure`
### ProcedureKitCloud
- [x] #523: `Capability.CloudKit`

### ProcedureKit
- [x] #569: `Profiler`

### ProcedureKitMac
- [x] #568:`TaskProcedure`

### ProcedureKitNetwork
- [x] #565: `NetworkDownloadProcedure`
- [x] #567: `NetworkUploadProcedure`
- [x] #563: `NetworkReachableProcedure` - now called `NetworkProcedure`

### ProcedureKitCloud
- [x] #542: `CloudKitProcedure`

### ProcedureKitMobile
- [x] #592: `UIProcedure` (formerly `UIOperation`)
- [x] #592: `AlertProcedure`

# Phase 4 - Documentation & Tooling
- [ ] Increase levels of documentation on public APIs - currently it's ~ 60%, actually dipped recently.
- [ ] Complete Wiki documentation & guide.
- [ ] Full SwiftPM support - currently doesn't actually seem to work
- [ ] Test integration via CocoaPods, Carthage & SwiftPM in CI
- [ ] Upload build artifacts in CI
- [ ] Add static analysis tools: CodeCov, Codebeat?
- [ ] Full test suite for `NetworkProcedure`

## Branches & Versions
- `master` Always has the last released version on it. Currently `v3.1`.
- `development` Is the base development branch for the next version. Currently, this work has yet to start in earnest. When it does, this branch will transition to Swift 3.0, Xcode 8 with a minimum version of iOS 9. There will be breaking changes here.
- `swift/2.2` Is the last version of the project which was built with Swift 2.2. Currently this is v3.1, and this branch exists in case of bug fixes which need to be released before v4.0 is ready.
- `swift/2.3` Is up-to-date with respect to `development` but builds using Swift 2.3 with Xcode 8, and is available for framework consumers who need to use the latest platform versions. For example, to builds for iOS 10, but without changing to Swift 3.0 - use this branch.
- `swift/3.0` Is a work-in-progress branch which works on many levels with Swift 3.0. However, this branch does not represent v4.0, and should be considered an intermediate solution for framework consumers who are working with Swift 3 already.

**Comment by marwey** [comment]
I was just starting a Swift 3 project based on current Xcode beta drops. So I am really happy to see you setting up ProcedureKit! ;-) 

Quick question regarding Swift 3: would V4 already build with Xcode 8 and Swift 3? Or would we need to wait for v5? Any rough estimates when we could use ProcedureKit in Swift 3 projects? 

Thanks again for all the effort you and others are putting into this!

**Comment by danthorpe** [comment]
@marwey - at the moment, there is a `swift/3.0` branch which is a little bit out of date, and works with Xcode 8 beta 3. We have had some troubles getting everything working with beta 4. You can use this to "get started" working on your own app using _ProcedureKit_ and Swift 3.0.

To reiterate, v4 of _ProcedureKit_ will be for Xcode 8 & Swift 3.0, it will drop support for iOS 8.

In terms of timelines - this is a quickly moving project and I anticipate that in a couple of weeks, the `development` branch of this project will be well into Phase 3 as detailed above.

**Comment by jad6** [comment]
That is great news @danthorpe, thank you for maintaining this excellent library. 

Since you are shooting for a Swift 3.0 + Xcode 8 v4 for ProcedureKit do you have any loose goals at integrating it (and the various smaller additional frameworks i.e. AlertOperations & company) with the [Swift Package Manager](https://swift.org/package-manager/#example-usage)? The Swift PM also has a loose Swift 3.0 deadline.

If your hands are too full I would be happy create some pull requests to make that happen on the `development` branch once PromiseKit is ready to be used as a dependency.

**Comment by danthorpe** [comment]
@jad6 - thanks!

The 2nd milestone of Phase 2 from above is to address the concern you've raised here. We've had a longstanding desire of wanting to ship a "core" framework which contains just the building blocks of functionality. Additional stuff like `AlertOperation` and all the CloudKit stuff will be delivered as a separate packages/modules/frameworks/pods which consumers can add depending on their needs. 

Ideally, this will almost certainly *just work* with SwiftPM - that would be my preferred solution. However I still want to support Carthage, CocoaPods etc - so part of this work will certainly be to provide the correct balance here.

Much of the details of this has yet to be hashed out, i.e. how will a framework consumer import the additional modules? Most of this will fall our of my current work on Phase 2 of _ProcedureKit_ over the next week.

Regarding contributing to _ProcedureKit_ - part of my reasoning for the move to an org is so that other people can become members. Anyone is welcome to get involved, and once the structure of the project is a bit more fleshed out for v4 I will invite some of the contributors from_Operations_. There will be plenty of changes / PRs needed to get `development` ready for v4 by Swift 3 - so, watch this page as they say! 😀

**Comment by blg-andreasbraun** [comment]
Count me in :) Looking forward to it. I do have some projects on Swift 3 already and this Framework ist definitely my preferred right now :D

**Comment by automactic** [comment]
@danthorpe, thank you for such an awesome framework. I cannot believe we are already in phase 3, so fast! But do you think it could be wiser to wait for Xcode 8 GM and then do the Swift 3 migration? As beta 9 & beta 10 (if there is one🙂) might come next week and introduce source breaking changes.

**Comment by danthorpe** [comment]
@automactic yeah, this is a very good point. I'm currently weighing up making the name changes in latest Xcode 8 beta but using Swift 2.3 vs ploughing ahead into Swift 3. In terms of pros and cons:

### Using Xcode 7, Swift 2.2
`pro`: Can focus on name changes, and project structure
`pro`: Would be able to make an intermediate release to help framework consumers transition from _Operations_ v3.1 -> _ProcedureKit_ v3.2?
`con`: Leaving a lot of work still to do (after looking through the beta 6 changes)

### Using Xcode 8, Swift 2.3
- pretty much the same as above I think

### Using Xcode 8, Swift 3.0
`pro`: Swift 3 changes are pretty huge - might as well get started on it as early as possible.
`pro`: Can focus on doing thin but deep changes. i.e. piece by piece move code into place so that it is correctly named, API is Swift 3 style, project is correctly organised. This gives full and correct usage for `ProcedureKit` in Swift 3.0 bit by bit.
`con`: It will make the jump from v3.1 to v4.0 pretty big, as framework consumers will need to transition names and language at the same time.

I think, to be realistic, iOS 10 will be released before I've finished either of the above two processes, which isn't great for framework consumers would are relying on _Operations_. So, doing a two phase move+rename, followed by Swift-3ing, will just take even longer. So at the moment, still leaning towards getting stuck into Swift 3.

If there is anything I have learned from adopting Swift is that it's generally always better to adopt as quickly as you can.

**Comment by jshier** [comment]
Looking at the `CHANGELOG` on [`apple/swift`](https://github.com/apple/swift/blob/master/CHANGELOG.md) it looks like the biggest breaking changes have landed in beta 6. We were able to [update Alamofire](https://github.com/Alamofire/Alamofire/pull/1413/files) over the last 2 days, as the removal of implicit bridging and the move to `id` being imported as `Any` instead of `AnyObject` required some breaking changes to the API. 

And as someone who is trying to build a Swift 3 app right now, the sooner ProcedureKit gets to a place where we can use it the better. Otherwise I have to keep working off of the branch of `Operations` (which I should get around to updating for beta 6 fairly soon, as beta 4/5 had runtime crashes due to Swift issues). All I need is the core functionality so whatever's in core will be enough.

**Comment by marwey** [comment]
@danthorpe fully agree! I believe many people will move to Swift 3 as soon as they can. It just doesn't make sense to invest anymore resources in Swift 2.x code.

**Comment by danthorpe** [comment]
Yep - so I think full steam ahead on Swift 3. Gonna be some breaking changes - it's unavoidable.

**Comment by JamieWhite** [comment]
Have you got a building Swift 3 branch at the moment?

**Comment by danthorpe** [comment]
Hi @JamieWhite, there is not a Swift 3 build of _Operations_ - the effort to resolve all of the naming conflicts is not worthwhile unfortunately. 

The `development` branch contains the work which is detailed at the top of this roadmap ticket. Should be able to make a `beta-1` version by the end of the week of core functionality.

The published releases are suitable for Swift 2.2 and Xcode 7, the `swift/2.3` branch is suitable for Swift 2.3 and Xcode 8 GM.

**Comment by marwey** [comment]
@danthorpe That sounds terrific. Looking very much forward to integrate core beta-1 in my Swift 3 project ;-)

**Comment by marwey** [comment]
@danthorpe Great progress on beta-1 today ;-) Also thanks a lot for detailing out the other beta phases. Too bad CloudKit support comes last. This is the one feature I would need most ;-) 
But it makes perfectly sense the way you described it. In any case, if you continue with this speed it won't take too long ;-)

**Comment by JamieWhite** [comment]
I'm really liking the new framework architecture with a core framework. My app has been listed as supporting Apple wallet and I never knew why. Now I realise it's because of Operations. It seems a bit odd to me that Apple doesn't just go off entitlements for this.

**Comment by danthorpe** [comment]
@JamieWhite - yeah, sorry about that - I agree with you, it's crazy.

For _ProcedureKit_ beta 1 - annoyingly there is a Swift 3.0 bug in Xcode 8 which is stopping it working in Carthage unless you use Debug builds. I've looked into it - but the way forward is not immediately clear. I need to raise the issue with the Swift people.

**Comment by JamieWhite** [comment]
Yeah I spotted that. I got it working by disabling optimisation. Do you know if it's possible to submit to the app store like this? I know it's a bad idea but at the moment out app is kind of in a closed beta.

Also what's the equivalent of `addFatalError(error)` for `GroupProcedure` ?

**Comment by misbell** [comment]
I tried the Swift 3.0 branch, but it's quite a bit out of date. version 4 beta 1 compiles like a champ though. well done. I just watched the Advanced NSOperations video so was pleasantly surprised to see your project. Looking forward to production version.

**Comment by marwey** [comment]
I was just wondering what the best practice is to add an observer to a ProcedureGroup? Use BlockObserver? Implement ProcedureObserver protocol? Something else?

**Comment by danthorpe** [comment]
@marwey - I would say it really depends on your use case. It's pretty flexible, but generally, it would only make sense to implement the protocol for when you want to provide something which is reusable. For example, see `TimeoutObserver`. Whereas, if you have a view controller which needs to respond to `Procedure` event changes - you will probably want to construct a `BlockObserver`.

I think for functionality inside your own `Procedure` subclasses - I would say that the `addWillExecuteObserver { }` etc etc is the best usage.

**Comment by marwey** [comment]
@danthorpe Thanks for clarification! 

One more question in this regard. How would I add the following BlockObserver:
                `let groupObserver = BlockObserver<GroupProcedure>(willFinish: { 
                          procedure, errors in
                          NSLog("Just finished!")
                   })` to a GroupProcedure? 

I was hoping I could use GroupProcedure's `func add(observer: GroupObserverProtocol)` method. Unfortunately BlockObserver is not implementing the GroupObserverProtocol?

**Comment by danthorpe** [comment]
Hi @marwey, you can do this:

```
let group = GroupProcedure(operations: [ BlockOperation { print("Hello world") }]) // etc
group.add(observer: BlockObserver(willFinish: { group, errors in 
    group.log.info(message: "Just finished!") // actually *not* finished yet, that's what the didFinish block is for.
}))
```

But if all you need is a will finish observer:

```
let group = GroupProcedure(operations: [ BlockOperation { print("Hello world") }])
group.addWillFinishObserver { group, errors in
    group.log.info(message: "Will finish...")
}
```

The `GroupObserverProtocol` is for getting callbacks when child `Foundation.Operation` instances are added to the group. And there is `GroupWillAddChildObserver` and `GroupDidAddChildObserver` and an API on `GroupProcedure`.

Also - probably best to ask questions in separate issues - I'd like to keep this issue focused on v4 roadmap.

**Comment by blg-andreasbraun** [comment]
Hi @danthorpe, I just noticed that in Procedure, there are two Methods that have an awkward argument label.

open func procedureWillFinish(withErrors: [Error]) { }
open func procedureDidFinish(withErrors: [Error]) { }

I think it should be 
open func procedureWillFinish(withErrors errors: [Error]) { }
open func procedureDidFinish(withErrors errors: [Error]) { }

Looking forward for the final release of 4.0 :D

**Comment by marwey** [comment]
or simply like this? 
`open func procedureWillFinish(with errors: [Error]) { }`
`open func procedureDidFinish(with errors: [Error]) { }`

**Comment by blg-andreasbraun** [comment]
@marwey sure, missed that :P

**Comment by marwey** [comment]
@blg-andreasbraun well, you spotted it in the first place ;-)

**Comment by blg-andreasbraun** [comment]
@danthorpe was ReachableOperation removed completely?
Or is it planned to integrate a reachable check implicitly into NetworkDataProcedure?

**Comment by danthorpe** [comment]
@blg-andreasbraun it's removed and won't be added back in quite the same way, this is because it was not best practice. `ReachableOperation` worked by _waiting_ until the client was determined to be reachable before executing the composed operation. This is explicitly against Apple's [best practices documentation](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/WhyNetworkingIsHard/WhyNetworkingIsHard.html#//apple_ref/doc/uid/TP40010220-CH13-SW2).

> **Important**: The SCNetworkReachability API is not intended for use as a preflight mechanism for determining network connectivity. You determine network connectivity by attempting to connect. If the connection fails, consult the SCNetworkReachability API to help diagnose the cause of the failure.

So, instead, what will happen is than `ReachableProcedure` will be a subclass of `RetryProcedure` which would then support Apple's recommended way of doing this. It would compose a generic `Procedure` subclass provided by the framework consumer for performing the network request. In this scenario, the composed procedure would be run, and if it cannot connect, it must finish with an error (conforming to a protocol), which can then be used by `ReachableProcedure` to start a listener to retry the procedure when the client re-connected.

I think `NetworkDataProcedure` should encapsulate all of this behaviour out of the box, but if you want to use `URLSession`'s delegate based APIs - then you'll need a custom `Procedure` subclass.

 I'll add an issue to keep track of this feature, as you're not the first to ask what will become of it. :)

Also, related, `ResilientNetworkProcedure` is aimed at retrying network procedures in light of client or server errors, to avoid flooding the network/server with retry requests.

**Comment by blg-andreasbraun** [comment]
@danthorpe

No big deal here, a coworker noticed it and asked me about it while he was migrating a project to Swift 3.
I told him to just try the request an handle the error.

The only thing everyone is missing here ist the AlertProcedure ;)

**Comment by danthorpe** [comment]
Totally. It's next on the list. 😀

**Comment by danthorpe** [comment]
@blg-andreasbraun FYI `development` now has `NetworkReachableProcedure` - feedback would be welcome as there is time to make changes here before Beta 5.

**Comment by blg-andreasbraun** [comment]
@danthorpe 

Sorry for the delay. Looks good to me. 

As for the NetworkProcedure, I think it might make sense if the add a NetworkObserver by default on iOS. Is there any reason why not?

**Comment by danthorpe** [comment]
@blg-andreasbraun - yeah, adding `NetworkObserver` by default would be great and makes sense. But it does overly complicate linking all the dependencies between the "sub frameworks", e.g. to build _ProcedureKitNetwork_ on iOS, we have to additionally build and link with _ProcedureKitMobile_.

**Comment by blg-andreasbraun** [comment]
@danthorpe - Would it be a big issue if NetworkObserver becomes a part of the Network Subframework, only available on iOS via @available or #if os(iOS)?

It would mean, that for a framework consumer to use it an import of the Network Subframework is needed.

**Comment by danthorpe** [comment]
@blg-andreasbraun - actually, yes, this is definitely a possibility. Potentially, it could be refactored so that only the iOS bits are in the _ProcedureKitMobile_ framework, and everything else, which is already abstracted away from this can go into _ProcedureKit_. Wouldn't even need wrapping in `#if os(iOS) #elseif`.

**Comment by JamieWhite** [comment]
Could we drop the `beta.5` from the `4.0.0.beta.5` version number? It makes it impossible to submit to Apple without manually going in and changing.

**Comment by danthorpe** [comment]
@JamieWhite - done in `development`, see #655. Will actually make a Beta 6 shortly. Before some potentially breaking changes regarding how we handle cancellation.

**Comment by JamieWhite** [comment]
Amazing. Thanks Dan. Looking forward to seeing what's changed in beta 6

**Comment by danthorpe** [comment]
Gonna close this now. _ProcedureKit_ has been v4 complete for a while now. There are still quite a few project maintenance goals which I'd like to do - but will set lower milestones for these.
