### ISSUE TITLE
ProcedureKit v5 Roadmap

### ISSUE THREAD

**Issue by danthorpe** [ProcedureKit/ProcedureKit#749]
This issue is to track the roadmap for development of _ProcedureKit_ v5.

_ProcedureKit_ v5 will be a major version and incorporate the following significant changes:

- Drop support for:
  * iOS 8 (minimum deployment target of iOS 9)
  * watchOS 2 (minimum deployment target of watchOS 3)
- Swift 4 (Xcode 9 new compiler)

## Goals

Additionally, we've got some significant project goals, which were not achieved during the development of _ProcedureKit_ v4.

- _Documentation driven development_. We want the documentation of the project to reflect the code in the project. (i.e. `master` documentation, `development` documentation). This is to exist on `http://procedure.kit.run`.

- Fill missing bits of functionality which didn't make it from _Operations_ -> _ProcedureKit_. Some of this will actually get done as part of _ProcedureKit_ v4.x releases. These include
    - [ ] `UserNotificationCondition` etc
    - [ ] Missing capabilities: ` Photos`, `Contacts` etc
    - [ ] Built-in support for `NSProgress`
    - [ ] Improvements to _ProcedureKitLocation_, in terms of stability and expansion to macOS, watchOS etc.

- Additional functionality. This is by no means locked down, but some ideas which have been floated for v5 include:
    - [ ] CoreData friendly procedures, for minimising setup & boilerplate code.
    - [ ] Expanded testing, particularly real-world testing of components such as networking and location.
    - [ ] Adaptors & helpers to plug into reactive UI components. This is a bit of an exploration item, but it seems that while _ProcedureKit_ is well suited for use in controller and data transport layers, there is a pretty large gap to get to view-presentation level code. Something which which is framework-agnostic would be great.
    - [ ] Support for socket-based networking.
    - ? Sound off in the comments if you have functionality which you'd like to see the framework support. We would love to have more contributors!

## Branches

Currently, we have the following setup:

- `master` (and tags) are public releases. Swift 3.1
- `development` (default branch) is active development branch. Swift 3.1

In the next couple of weeks, we will branch `development` to support development of _ProcedureKit_ v4.x releases:

- `master` (and tags) are public releases.
- [`v4/development`](https://github.com/ProcedureKit/ProcedureKit/tree/v4/development) (or something similar) will be for _ProcedureKit_ v4.x work
- `development` will become Xcode 9 / Swift 4 / iOS 9+  _ProcedureKit_ v5 work
- `releases/5.0.0.beta-n` will be for   _ProcedureKit_ v5 pre-release betas.

**Comment by SD10** [comment]
@danthorpe I've just recently started looking at Operations and would like to contribute to this project. That being said, I need to familiarize myself with the codebase. If you have some starter tasks feel free to send them my way.

**Comment by danthorpe** [comment]
Thanks @SD10, that would be great! We put the [`you can do this`](https://github.com/ProcedureKit/ProcedureKit/issues?q=is%3Aopen+is%3Aissue+label%3A%22you+can+do+this%22) label on starter tasks, which are always a big help. The only one we have labelled is actually being worked on by @swiftlyfalling at the moment.

At the moment, work for v5 is very much at an exploratory stage, and we haven't fleshed out much of anything just yet.

**Comment by mRs-** [comment]
I would like to help to form the Documentation in a better state. Currently there are so many entry points and all are outdated. But I don't know where to start. Which one is really the future usage of the documentation? Is the documentation based in code and generated by a tool like jazzy? Currently it's a bit confusing because I couldn't find a guideline for this.

**Comment by danthorpe** [comment]
Hi @mRs- Hopefully the release nots for the latest version [4.3.0](https://github.com/ProcedureKit/ProcedureKit/releases/tag/4.3.0) explain the direction for the documentation best.

Writing guides and documentation is hard. However it is generated from the source code via Jazzy. So you can contribute by adding class descriptions and guides in the source, or add to the general/overall programming guide in the `Documentation/Guides/` directory. To see what the docs look like, run `$ jazzy --config .jazzy.json` from the project root. The documentation is published at `http://procedure.kit.run/development/`.

**Comment by danthorpe** [comment]
In another area, Apple have changed the minimum os requirements of some key frameworks on the watchOS platform. CoreLocation and CloudKit now require watchos 3+, whereas with Xcode 8, watchOS 2.2 is allowed.

This is a major breaking change, which means that _ProcedureKit_ v4.* will fail when building for watchOS 2.2. Therefore v5 will update the minimum watchos target to 3.

**Comment by mRs-** [comment]
Awesome I will start to add documentation here, because we need it I think :)

**Comment by blg-andreasbraun** [comment]
@danthorpe Any news on the v5? Or skip it and wait for Swift 5? :D

**Comment by danthorpe** [comment]
@blg-andreasbraun yeah, at the moment Swift 4 is done without any breaking changes for v4.5

More than likely v5 of ProcedureKit will align with Swift 5.
